// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIH5M8q7xDP32DNuCDrV9HZePsoID_NNc',
    appId: '1:150529320368:web:3b48a85652be27f2222275',
    messagingSenderId: '150529320368',
    projectId: 'noteapp-54fe2',
    authDomain: 'noteapp-54fe2.firebaseapp.com',
    storageBucket: 'noteapp-54fe2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjvsIOtlOfi8ywJPW6BrsbT9vgmAwXZzE',
    appId: '1:150529320368:android:b563c5a454f6fd58222275',
    messagingSenderId: '150529320368',
    projectId: 'noteapp-54fe2',
    storageBucket: 'noteapp-54fe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTHH38qNSrM-FVWn_LODD1zZIEXz-B0ik',
    appId: '1:150529320368:ios:f7bebe88a272d3e8222275',
    messagingSenderId: '150529320368',
    projectId: 'noteapp-54fe2',
    storageBucket: 'noteapp-54fe2.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTHH38qNSrM-FVWn_LODD1zZIEXz-B0ik',
    appId: '1:150529320368:ios:f7bebe88a272d3e8222275',
    messagingSenderId: '150529320368',
    projectId: 'noteapp-54fe2',
    storageBucket: 'noteapp-54fe2.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIH5M8q7xDP32DNuCDrV9HZePsoID_NNc',
    appId: '1:150529320368:web:2406b4206fff9c86222275',
    messagingSenderId: '150529320368',
    projectId: 'noteapp-54fe2',
    authDomain: 'noteapp-54fe2.firebaseapp.com',
    storageBucket: 'noteapp-54fe2.appspot.com',
  );
}
